spring:
  application:
    name: taskmanager
  data:
    mongodb:
      uri: mongodb+srv://arunalubamunusinghe75:QeP0wWDlCallO6zI@cluster0.n5poqff.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: TaskManager

server:
  port: 8080
  servlet:
    context-path: /api/taskmanager/
  error:
    include-exception: true
    include-message: always